### ISSUE TITLE
Attack OwnMod Issue

### ISSUE THREAD

**Issue by Valdacil** [drexl93/pf2e-shapeshifting#1]
First, thank you for these macros.  This is exactly what I needed right now.

I do see an issue with OwnMod however as our group determined that if you combine the text of unarmed attack (If your unarmed attack bonus is higher, you can use that instead) with Wild Shape's "When you choose to use your own attack modifier while polymorphed, you gain a +2 status bonus" to say that occurs before the comparison.  In other words, if your own unarmed attack modifier is +9 and the form's attack modifier is +9, adding the +2 would make your own modifier +11 and thus you can use that.  So technically it is fudging the rule about if your unarmed attack bonus is _HIGHER_ to if your unarmed attack bonus is _equal or greater_.

**Comment by drexl93** [comment]
Thanks for catching that! It should be fixed now, so the attack modifier that will used is either the Form's Bonus, or your base mod + 2 if that is higher. This also accounts for if your mod if just 1 lower than the Form's Bonus, but you can choose to use it and gain +2, making it 1 greater than the Form's.

Also added support for Handwraps of Mighty Blows. Let me know if things work better now!
