### ISSUE TITLE
How do I set this up for my character?

### ISSUE THREAD

**Issue by Handyfon** [drexl93/pf2e-shapeshifting#2]
Just using the macro doesn't seem to work for me, it would be nice to have a checklist what your character needs in order for the macros to function 👍 

I love the conzept but I really just can't get it to work.

**Comment by drexl93** [comment]
Hey there. Firstly, do make sure you've installed the Furnace. The macros all need that to function. 

For the Wild Shape Macro, you need to have the specific feat whose forms you want access to in your character's feat list. The macro essentially populates the available options from what feats you have.  So if you have "Wild Shape", it gives you access to Pest Form and Animal Form, and if you have "Ferocious Shape" you'll have access to the dinosaur forms, et cetera.

The Spell Shape macro doesn't need any of that - you should be able to use it and transform into whatever shape you'd like. It of course doesn't include Wild Shape specific rules (like the +2 attack bonus for using your own unarmed attack modifier), or feat specific bonuses (like fire resistance from Elemental Shape).

Once transformed, the Shape Strike macro should offer you the correct attack options.
