### ISSUE TITLE
token not changing

### ISSUE THREAD

**Issue by quentfisto** [drexl93/pf2e-shapeshifting#3]
when I try to use the macro (either wild shape or spell shape), everay values change to the right one (as far as I can tell anyways), but the token does not change, neither the image or the size.
I have the images I'm using to test the macro in the same folder as the original image for the token, and have tried with the gm and the trusted permission. 
Is there something I'm not doing right ?

**Comment by drexl93** [comment]
Would you mind navigating to the developer console (that's hitting F12 in the Foundry window/Chrome if you use Windows) and letting me know if you see any errors? And if you do, what do they say?

**Comment by quentfisto** [comment]
There is an error message that says : 
Uncaught (in promise) TypeError: Cannot read property 'totalModifier' of undefined
    at transform (eval at callScriptMacroFunction (Macros.js:176), <anonymous>:1097:96)

**Comment by drexl93** [comment]
A couple questions: 
- Under the Actions tab of your character sheet, do you have the "Fist" option? Did you change its name or any details?
- Are you using Handwraps of Mighty Blows? Did you change its name or any details?

Would you mind exporting the character you're testing on and sending me the file via Discord? (Some Knucklehead#4725). Thanks!

**Comment by quentfisto** [comment]
I got a translation module that renamed it, I'll try renaming it

**Comment by quentfisto** [comment]
It's working when i deactivate my translation module, so that's fixed.

**Comment by drexl93** [comment]
I'm glad to hear it! Out of curiosity, what module is it? I just want to see if I can find a workaround for you.

**Comment by quentfisto** [comment]
https://gitlab.com/pathfinder-fr/foundryvtt-pathfinder2-fr
It's this one. I changed the line in your code that checked the "Fist" bonus by "Poing" (the french word) and it worked perfectly.

**Comment by drexl93** [comment]
Perfect! And if you ever get Handwraps of Mighty Blows, you just need to make sure a similar change and you should be golden.
