### ISSUE TITLE
Token not changing back

### ISSUE THREAD

**Issue by Gliber9** [drexl93/pf2e-shapeshifting#4]
I created a token for animal form CharacterNameApe.png

Shape changing works perfectly, and the token changes to Ape. But when I select Revert, it stays in the CharacterNameApe.png token, meaning I have to manually go in as a GM and edit the token image. Is there a way to have it revert back to the original token name or know to remove Ape from the token image name and then set that image?

Thanks,

Tom

**Comment by drexl93** [comment]
Hey! I've pushed an update that I think may have fixed your bug. Let me know if it still persists.

**Comment by Gliber9** [comment]
The flow of the transformation seems faster overall, which is great. Sadly, the token still retains its new image and does not revert.

CharacterNameApe.png is still the token name after everything is done reverting back to normal form, making manual token image adjustment necessary.

Tom

**Comment by drexl93** [comment]
Would you mind doing the following steps in order for me and letting me know if there's still a problem?

1. Disable the PF2e Shapeshifting Module in your world and delete any macros from it that you may have imported
2. Delete the PF2e Shapeshifting Module
3. Install the PF2e Shapeshifting Module
4. Enable the PF2e Shapeshifting Module
5. In your world, make sure you're using the macros drawn from the pf2e-shapeshifting compendium
6. Test image change transformation

**Comment by Gliber9** [comment]
Works like a charm now.

Thanks for great module. It's a time saver.
